version: '3'
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - psgl:/var/lib/postgresql/data/

  parserall:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "pipenv run python db_tools.py connect_db &&
                      pipenv run python stock_parser.py ticker &&
                      pipenv run python stock_parser.py stock_all &&
                      pipenv run python main.py"
    env_file:
      - .env
    depends_on:
      - postgres

  parseroneday:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "pipenv run python stock_parser.py stock_today &&
                      pipenv run python main.py"
    env_file:
      - .env
    depends_on:
      - postgres

volumes:
  psgl: